### ISSUE TITLE
Download options

### ISSUE THREAD

**Issue by IzzySoft** [afaneca/myfin-android#31]
This looks like a real interesting project! Do you plan to make the app available outside Google's walled garden as well (e.g. by attaching the APKs to their corresponding [releases](https://github.com/afaneca/myfin-android/releases))? Not everybody has access to PlayStore, but the possibility of sideloading would make a good option for them. Thanks for considering!

**Comment by afaneca** [comment]
Thank you for your interest in the project. I'll make signed apk's available through the release assets for each new release from now on.

**Comment by IzzySoft** [comment]
Great, thanks! Can you drop me a note here when the first APK is available? I've just checked, and the latest release does not (yet?) have one.

**Comment by IzzySoft** [comment]
Ah, my bot was faster :rofl: So your app will [become available in my repo](https://apt.izzysoft.de/packages/com.afaneca.myfin/) with the next sync in about 2.5h from now, making it possible for interested people to use their [F-Droid](https://f-droid.org/) client to install it and keep it updated (as long as you continue providing the APKs with future releases). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link there e.g. from your Readme here, @afaneca :smiley: 

Thanks again for providing your app as FOSS – and for making it available now also for those outside Google!
