### ISSUE TITLE
Issue with GaugeSeekBar

### ISSUE THREAD

**Issue by IzzySoft** [afaneca/myfin-android#43]
Updated signatures for my scanner just reported MyFin includes [GaugeSeekBar](https://github.com/10clouds/GaugeSeekBar), which declares no license and thus is not considered FOSS (but just "source available"). Do you know what license it falls under – or could it maybe replaced by another library that is FOSS? After all, it also seems to be unmaintained (last commit was more than 5 years ago).

According to its description, GaugeSeekBar is "a library for displaying round seek bar view". So potential replacements could include:

* [croller](https://github.com/harjot-oberai/Croller) (MIT): "a circular seekbar with a control knob" (2018)
* [SeekArc](https://github.com/neild001/SeekArc) (MIT): "circular SeekBar view for Android" (2015)
* [CircularSeekBar](https://github.com/tankery/CircularSeekBar) (Apache-2.0): "a circular progress bar" (2023)

(results from said signatures searched case-insensitively for "seekbar") or

* [Gauge](https://github.com/Pygmalion69/Gauge) (Apache-2.0): "a Gauge View for Android" (2023)
* [GaugeView](https://github.com/CodeAndMagic/GaugeView) (Apache-2.0): "library for drawing gauges on Canvas" (2015)

(same with "gauge"). Unfortunately, most of them seem also out-of-development (see the year of last commit), but hopefully one of the recent candidates fits as replacement. Until then, I unfortunately have to mark your app in my repo with the corresponding anti-feature (`NonFreeComp`: contains non-free components) – which will of course be removed as soon as the cause is gone.

**Comment by afaneca** [comment]
I'm currently using a modified version (mantained by me) of that specific library. Replacing it is actually in my roadmap so it should  happen in one of the next few releases.

**Comment by IzzySoft** [comment]
Thanks! That's helpful. So I mark it as mentioned above until that release is available. My scanner should inform me once it's gone so I shall remove the flag again – but feel free to drop me a note here when it's ready so I'm prepared :wink:

**Comment by afaneca** [comment]
Dependency removed w/ #58.

**Comment by IzzySoft** [comment]
Thanks – and confirmed! The AntiFeature will be removed from the app's listing in my repo with the next sync (around 5 pm UTC) with the new release showing up (already done in "staging").

Would you like to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to [link there](https://apt.izzysoft.de/packages/com.afaneca.myfin/) from your Readme here? You could also consider [applying](https://gitlab.com/fdroid/rfp/-/issues/) for a listing with F-Droid.org, now that the "non-free component" is gone.
